apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
      annotations:
        # The OpenTelemetryCollector (mode sidecar) resource must be created first
        sidecar.opentelemetry.io/inject: "true"
        # The Instrumentation resource must be created first
        instrumentation.opentelemetry.io/inject-nodejs: "true"
    spec:
      containers:
        - name: myapp
          image: nzuguem/helloworld-nodejs
          ports:
            - containerPort: 8080